name:                jq-hs
version:             0.1.0.0
github:              "tobiasbrandy/jq-hs"
license:             BSD3
author:              "Tobias Brandy"
maintainer:          "tbrandy@itba.edu.ar"
copyright:           "2022 Tobias Brandy"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            educational

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tobiasbrandy/jq-hs#readme>

dependencies:
- base
- bytestring
- array
- text
- text-show
- pretty-simple
- scientific
- hashable
- containers
- unordered-containers
- optparse-applicative
- file-embed

library:
  source-dirs: src

executables:
  jqhs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jq-hs

tests:
  jqhs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jq-hs
    - HUnit

build-tools: 
  - happy
  - alex

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - RecordWildCards
  - ApplicativeDo
  - BangPatterns
  - StrictData
  - TupleSections
